language: node
node_js:
  - "12.7.0"

env:
  global:
    - secure: "Zwmp6utkoVZ70n2xEGwhuUpt/82HP4ZkJyFlZB5/Ew0hdA1MyvJzn92owFIeNzh152ALzZCGFH3JGVMXp8NHkE6gpGF4XChMg3xWxOlfqghNHYMD2wkN6Nh7fT7btt+noNhlpgGL1PiLH0dYf+zeh90fKZRk9YTGjn+nSXKLNWbehPj20HDpJ5LCRH+391e3LQiFmolHS4QxC5rp8dEdtqGErdkmijupSxKxg0X0OOwsXwHyrkn+e4CJCczUM3HSxuyrAsbkntR4QKdCwgV9RaMmVyCUhKLRJETKa5A2BbGMAwq76onOXpko5+EAEVHv9fofIEbv9ePw1iHruJuI/ZvrfeXTt2Ea/tPN+0fFJ9nIu4fJpGm3KIFFh/PLLSfeaLq+yff6vvCSHPiXRJLHoeFce76Y6ghtGZm1hbnezv7C5nGPx1TN5t1IdW7MpvuBPp686N/loBUXRetm8wDgyNDWQXhRvIjY74swuGtELYNozcYWLw7Kg5QnQ+wMFaFvJdybZc+Z9wsMpP9/J8J6UObqbOk+Hfl4yBI+HS2Ls3rZ/qdrzlIf6PmDGnjmr6syxoy34gJZDyrcOnNSkU29T1siS2Ew4jOeOHleXg4SGPYIr4AXOla45OI/p/MvcwJvnUERehLO6aDj4J+zDTk1msXEbuzinWK6990zkESqb2U="

cache:
  npm: false

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - npm install

script:
  - ng lint
  - ng test --watch=false --code-coverage
  - ng e2e
  - ng build
  - codecov

addons:
  chrome: stable
  coverity_scan:
    project:
      name: "aubrey-y/findmyfood"
      description: "find your food"
    notification_email: aubreym.yan@gmail.com
    build_command: "ng build"
    branch_pattern: coverity_scan
